### ISSUE TITLE
error when using the instructions in readme

### ISSUE THREAD

**Issue by QiongwenXu** [eth-sri/fastsmt#4]
Hi, I followed the instructions in readme step by step. When I ran `python synthesis/learning.py -h`, I met the following error. Could you pls help me have a look? Thanks.
```
(venv) :~/Documents/research/fastsmt/fastsmt$ python synthesis/learning.py -h
WARNING:root:fastText could not be imported (only needed to run fastText model).
Traceback (most recent call last):
  File "synthesis/learning.py", line 28, in <module>
    from fastsmt.synthesis.search.models import ApprenticeModel, FastTextModel, RandomModel, BFSModel
  File "/home/xuqiongwen/Documents/research/venv/lib/python3.6/site-packages/fastsmt-1.0-py3.6.egg/fastsmt/synthesis/search/models.py", line 30, in <module>
ImportError: cannot import name 'joblib'
```
other info: ubuntu 16.04, python 3.6.11(since python 3.5 does not support matplotlib), z3: 4.6.2

**Comment by mbalunovic** [comment]
Thanks for reporting the issue, the problem was that code doesn't work with the latest version of scikit-learn.
I fixed it now by setting scikit-learn version to 0.20, could please you try to reinstall it and check if it works now?
